server:
  port: 2020
  
spring:
  application:
    name: API-CLOUD-GATEWAY
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        -  Path=/greet
      - id: welcomw-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
          
          